### ISSUE TITLE
超齊百萬字典檔有許多重複的詞彙

### ISSUE THREAD

**Issue by doggy8088** [samejack/sc-dictionary#2]
我統計總共有 70,607 個重複的詞彙。

**Comment by doggy8088** [comment]
@samejack 請問你這份是怎樣算出來的？裡面有許多無意義的詞彙，好奇你的擷取方法為何？

**Comment by samejack** [comment]
@doggy8088 年代久遠，我印象中是合併一些中文分詞的字典檔完成的，前幾年都在玩 ElasticSearch 需要比較大量的字典檔，所以合併整合了中文繁體與簡體的資料。
